from common.consts import SWORD, AXE, BOW

# Scrypt Consts
SCRYPT_KEY_LENGTH = 32
SCRYPT_N = 2 ** 14
SCRYPT_R = 8
SCRYPT_P = 1

ARM_LENGTH_MULTIPLIER = 10

# Game consts
ATTACK_BBOX_LENGTH = 100
FRAME_TIME = 1 / 60
MAX_SLOT = 6

# Server communication ports
ROOT_SERVER2SERVER_PORT = 35000

# other
MOB_SIGHT_WIDTH = 700
MOB_SIGHT_HEIGHT = 700
MOB_ERROR_TERM = 30
RANGED_OFFSET = 270

PET_SPAWN_X_DELTA = 300
PET_SPAWN_Y_DELTA = 300

BAG_SIZE = 3
