"""General Common consts"""
import struct
from typing import Tuple

from cryptography.hazmat.primitives.asymmetric.ec import SECP384R1

INT_SIZE = 4
UUID_SIZE = 36

# Format 
MESSAGE_ENDIANESS = ">"
UUID_FORMAT = f'{UUID_SIZE}s'
SEQUENCE_FORMAT = 'q'
POSITION_FORMAT = 'll'
# [chat msg, attack, attack dir, equipped id]
ACTIONS_FORMAT = '255si?ffi'
CLIENT_FORMAT = MESSAGE_ENDIANESS + SEQUENCE_FORMAT + POSITION_FORMAT + ACTIONS_FORMAT

NUMBER_OF_ENTITIES_FORMAT = 'l'
NUMBER_OF_TOOLS = 6
TOOLS = 'i' * NUMBER_OF_TOOLS
HEALTH = 'i'
NEW_CHAT_MSG = '255s'
TYPE_FORMAT = 'i'
DIRECTION_FORMAT = 'ff'
TOOL_FORMAT = 'l'
ENTITY_FORMAT = TYPE_FORMAT + UUID_FORMAT + POSITION_FORMAT + DIRECTION_FORMAT + TOOL_FORMAT
ENTITY_NUM_OF_FIELDS = 7
SERVER_HEADER_FORMAT = MESSAGE_ENDIANESS + TOOLS + NEW_CHAT_MSG + POSITION_FORMAT + HEALTH + NUMBER_OF_ENTITIES_FORMAT
SERVER_HEADER_SIZE = struct.calcsize(SERVER_HEADER_FORMAT)
# Redirect msg
IP_FORMAT = "15s"
LOGIN_RESULT_FORMAT = "?l"
"""success status + error message length"""

REDIRECT_FORMAT = MESSAGE_ENDIANESS + UUID_FORMAT + IP_FORMAT + LOGIN_RESULT_FORMAT

# sizes of stuff
NUM_NODES = 1

# Some defaults
EMPTY_UUID = "0" * UUID_SIZE

# Useful graphics consts
CLIENT_HEIGHT = 60
CLIENT_WIDTH = 45

WORLD_HEIGHT = 675 * 64
WORLD_WIDTH = 675 * 64

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PROJECTILE_HEIGHT = 68
PROJECTILE_WIDTH = 20

BOT_HEIGHT = 20
BOT_WIDTH = 20

# Types
Pos = Tuple[int, int]
Addr = Tuple[str, int]
Dir = Tuple[float, float]

# Server configurations
NODE_PORT = 42069
DEFAULT_NODE_IP = "127.0.0.1"
RECV_CHUNK = 1024
THREADS_COUNT = 1
NODE_COUNT = 1

# Networking conventions
DEFAULT_POS_MARK = (-1, -1)
DEFAULT_DIR = (0.0, 0.0)
DEFAULT_ADDR = (DEFAULT_NODE_IP, -1)

# Useful player information
SPEED = 5
MAX_HEALTH = 100
MIN_HEALTH = 0
PROJECTILE_SPEED = 5
ARROW_OFFSET_FACTOR = 100

# Tools
EMPTY_SLOT = 0
SWORD = 1
AXE = 2
BOW = 3

# Entity types
PLAYER_TYPE = 0
PROJECTILE_TYPE = 1
BOT_TYPE = 2
OBSTACLE_TYPE = 3

# ECDH Consts
COMPRESSED_POINT_SIZE = 49
ELLIPTIC_CURVE = SECP384R1()
SHARED_KEY_SIZE = 32

# Some temporary consts
ROOT_IP = "127.0.0.1"
ROOT_PORT = 30000
